### ISSUE TITLE
uzerp-app-dev: FOP fails to produce output in 22.05.1

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp-containers#2]
FOP fails to produce PDF output.

```
fop -xsl 1660751268.xsl -xml 1660751268.xml test.pdf
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
[warning] /usr/bin/fop: Unable to locate avalon-framework in /usr/share/java
[warning] /usr/bin/fop: Unable to locate fontbox in /usr/share/java
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/avalon/framework/configuration/ConfigurationException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.apache.xmlgraphics.util.Service.providers(Service.java:85)
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.discoverClasspathImplementations(ImageImplRegistry.java:105)
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:81)
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:89)
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<clinit>(ImageImplRegistry.java:73)
	at org.apache.xmlgraphics.image.loader.ImageManager.<init>(ImageManager.java:64)
	at org.apache.fop.apps.FopFactoryBuilder$FopFactoryConfigImpl.<init>(FopFactoryBuilder.java:387)
	at org.apache.fop.apps.FopFactoryBuilder.<init>(FopFactoryBuilder.java:89)
	at org.apache.fop.apps.FopFactoryBuilder.<init>(FopFactoryBuilder.java:80)
	at org.apache.fop.apps.FopFactoryBuilder.<init>(FopFactoryBuilder.java:70)
	at org.apache.fop.cli.CommandLineOptions.setUserConfig(CommandLineOptions.java:1018)
	at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:173)
	at org.apache.fop.cli.Main.startFOP(Main.java:166)
	at org.apache.fop.cli.Main.main(Main.java:214)
Caused by: java.lang.ClassNotFoundException: org.apache.avalon.framework.configuration.ConfigurationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

**Comment by steveblamey** [comment]
Two packages need to be installed:

libavalon-framework-java (fop works after this is added)
libfontbox-java (removes the second warning)

**Comment by steveblamey** [comment]
Solved, see: https://github.com/uzerpllp/uzerp-containers/commit/bf6bc7d95bdbe50ad0a154919c145402f6b1f213
